packages:
  - name: preregistration-verify
    actions:
      - name: preregistration-verify
        runtime: 'python:default'
  - name: kyc-verify
    actions:
      - name: kyc-verify
        runtime: 'python:default'
